"""add movie catalog models

Revision ID: 71811371f26d
Revises: 58ec1bf67ee9
Create Date: 2026-09-16 14:13:05.974730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '71811371f26d'
down_revision: Union[str, Sequence[str], None] = '58ec1bf67ee9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('activation_token', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('activation_token_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.create_unique_constraint(op.f('uq_users_activation_token'), 'users', ['activation_token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_users_activation_token'), 'users', type_='unique')
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_column('users', 'activation_token_expires_at')
    op.drop_column('users', 'activation_token')
    # ### end Alembic commands ###
